In [1]:
# !pip install jsonlines
!pip install -U torch_geometric
!pip install -U torch

Collecting torch_geometric
  Downloading torch_geometric-2.6.1-py3-none-any.whl.metadata (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 kB 1.8 MB/s eta 0:00:00
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from torch_geometric) (3.11.15)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch_geometric) (2025.3.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch_geometric) (3.1.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from torch_geometric) (2.0.2)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.11/dist-packages (from torch_geometric) (5.9.5)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.11/dist-packages (from torch_geometric) (3.2.3)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from torch_geometric) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from torch_geometric) (4.67.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->torch_geometric) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->torch_geometric) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->torch_geometric) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->torch_geometric) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->torch_geometric) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->torch_geometric) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->torch_geometric) (1.19.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch_geometric) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->torch_geometric) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->torch_geometric) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->torch_geometric) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->torch_geometric) (2025.1.31)
Downloading torch_geometric-2.6.1-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 19.3 MB/s eta 0:00:00
Installing collected packages: torch_geometric
Successfully installed torch_geometric-2.6.1
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (2.6.0+cu124)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch) (4.13.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch) (2025.3.2)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch) (3.0.2)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 2.4 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 80.8 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 88.0 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 49.7 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.5 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.0 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 38.4 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 17.6 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 2.7 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 104.5 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
from pathlib import Path
DATA_FOLDER = Path('/content/drive/MyDrive/DSCI599/data')
MODEL_FOLDER = Path('/content/drive/MyDrive/DSCI599/models')

# load data

In [4]:
csv_files = list(DATA_FOLDER.glob("*.csv"))
for f in csv_files:
  print(f)

/content/drive/MyDrive/DSCI599/data/1464217200.csv
/content/drive/MyDrive/DSCI599/data/graph_labels.csv
/content/drive/MyDrive/DSCI599/data/normal_labels.csv
/content/drive/MyDrive/DSCI599/data/df_cluster.csv
/content/drive/MyDrive/DSCI599/data/umap.csv
/content/drive/MyDrive/DSCI599/data/new_graph_labels.csv
/content/drive/MyDrive/DSCI599/data/new_raw_labels.csv
/content/drive/MyDrive/DSCI599/data/big_gt.csv

In [5]:
import pandas as pd

df = pd.read_csv(csv_files[0])
df.head()

,int_source_ip,destination_port,protocol,num_scanned_destination_ips,num_unique_flows,num_packets,same_packet_size_flag,avg_packet_size,num_unique_Bs_scanned,num_unique_Cs_scanned,num_unique_Ds_scanned,num_scanned_24_blocks,num_non_conficker_destinations,time_activity,ip_scanned_rate
0,16968188,23,6,316.0,316.0,945.0,1.0,60.0,175.0,182.0,177.0,316.0,65.0,3540.0,0.089266
1,17372742,445,6,661.0,661.0,1322.0,1.0,48.0,125.0,234.0,126.0,654.0,661.0,3540.0,0.186723
2,17384594,445,6,169.0,169.0,329.0,1.0,48.0,98.0,117.0,89.0,169.0,169.0,3360.0,0.050298
3,17400985,23,6,256.0,256.0,762.0,1.0,60.0,1.0,1.0,256.0,1.0,128.0,0.0,-1.000000
4,17401572,445,6,571.0,571.0,1142.0,1.0,48.0,124.0,232.0,125.0,564.0,571.0,3540.0,0.161299

In [6]:
print("Number of unique source_ips")
len(df[['int_source_ip']].value_counts())

Number of unique source_ips

123025

In [7]:
print("Number of unique (source_ip, destination_port):")
len(df[['int_source_ip', "destination_port"]].value_counts().index)

Number of unique (source_ip, destination_port):

132778

In [8]:
df.groupby(['int_source_ip', "destination_port"])['protocol'].count().mean()

np.float64(1.0013405835304041)

In [9]:
random_ip = df['int_source_ip'].sample(1).tolist()
df[df['int_source_ip'].isin(random_ip)]

,int_source_ip,destination_port,protocol,num_scanned_destination_ips,num_unique_flows,num_packets,same_packet_size_flag,avg_packet_size,num_unique_Bs_scanned,num_unique_Cs_scanned,num_unique_Ds_scanned,num_scanned_24_blocks,num_non_conficker_destinations,time_activity,ip_scanned_rate
41269,1476227750,23,6,296.0,296.0,887.0,1.0,60.0,166.0,178.0,178.0,295.0,69.0,3540.0,0.083616

In [10]:
random_ip = df['int_source_ip'].sample(1).tolist()
df[df['int_source_ip'].isin(random_ip)]

,int_source_ip,destination_port,protocol,num_scanned_destination_ips,num_unique_flows,num_packets,same_packet_size_flag,avg_packet_size,num_unique_Bs_scanned,num_unique_Cs_scanned,num_unique_Ds_scanned,num_scanned_24_blocks,num_non_conficker_destinations,time_activity,ip_scanned_rate
20949,991901637,23,6,2029.0,2029.0,6069.0,1.0,60.0,239.0,256.0,256.0,1993.0,552.0,3540.0,0.573164

In [11]:
import numpy as np
df.loc[(df == np.inf).any(axis=1), 'avg_packet_size'] = -1

drop some features nmot used in GCN

In [12]:
not_features = [
    "num_non_conficker_destinations",
    "same_packet_size_flag",
]

df = df.drop(columns = not_features)
df.head()

,int_source_ip,destination_port,protocol,num_scanned_destination_ips,num_unique_flows,num_packets,avg_packet_size,num_unique_Bs_scanned,num_unique_Cs_scanned,num_unique_Ds_scanned,num_scanned_24_blocks,time_activity,ip_scanned_rate
0,16968188,23,6,316.0,316.0,945.0,60.0,175.0,182.0,177.0,316.0,3540.0,0.089266
1,17372742,445,6,661.0,661.0,1322.0,48.0,125.0,234.0,126.0,654.0,3540.0,0.186723
2,17384594,445,6,169.0,169.0,329.0,48.0,98.0,117.0,89.0,169.0,3360.0,0.050298
3,17400985,23,6,256.0,256.0,762.0,60.0,1.0,1.0,256.0,1.0,0.0,-1.000000
4,17401572,445,6,571.0,571.0,1142.0,48.0,124.0,232.0,125.0,564.0,3540.0,0.161299

In [29]:
from sklearn.preprocessing import MinMaxScaler

proc_df = pd.DataFrame(MinMaxScaler().fit_transform(df), columns=df.columns)
proc_df['int_source_ip'] = df['int_source_ip']
proc_df['destination_port'] = df['destination_port']

proc_df['protocol'] = df['protocol']
proc_df.head()

,int_source_ip,destination_port,protocol,num_scanned_destination_ips,num_unique_flows,num_packets,avg_packet_size,num_unique_Bs_scanned,num_unique_Cs_scanned,num_unique_Ds_scanned,num_scanned_24_blocks,time_activity,ip_scanned_rate
0,16968188,23,6,0.000022,0.004822,0.000068,0.000174,0.731092,0.709804,0.690196,0.005244,1.000000,0.000067
1,17372742,445,6,0.000047,0.010086,0.000096,0.000140,0.521008,0.913725,0.490196,0.010870,1.000000,0.000073
2,17384594,445,6,0.000012,0.002579,0.000023,0.000140,0.407563,0.454902,0.345098,0.002797,0.949153,0.000064
3,17400985,23,6,0.000018,0.003906,0.000055,0.000174,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
4,17401572,445,6,0.000041,0.008713,0.000082,0.000140,0.516807,0.905882,0.486275,0.009372,1.000000,0.000071

ohe the procotol

In [25]:
df['protocol'].value_counts()

protocol
6     109596
17     21136
1       2224
Name: count, dtype: int64

In [30]:
proc_df['is_tcp'] = 0
proc_df.loc[proc_df['protocol'] == 6, 'is_tcp'] = 1

proc_df['is_udp'] = 0
proc_df.loc[proc_df['protocol'] == 17, 'is_udp'] = 1

# proc_df['is_icmp'] = 0
# proc_df.loc[proc_df['protocol'] == 1, 'is_icmp'] = 1

# proc_df = proc_df.drop(columns = ['protocol'])
proc_df.head()

,int_source_ip,destination_port,protocol,num_scanned_destination_ips,num_unique_flows,num_packets,avg_packet_size,num_unique_Bs_scanned,num_unique_Cs_scanned,num_unique_Ds_scanned,num_scanned_24_blocks,time_activity,ip_scanned_rate,is_tcp,is_udp
0,16968188,23,6,0.000022,0.004822,0.000068,0.000174,0.731092,0.709804,0.690196,0.005244,1.000000,0.000067,1,0
1,17372742,445,6,0.000047,0.010086,0.000096,0.000140,0.521008,0.913725,0.490196,0.010870,1.000000,0.000073,1,0
2,17384594,445,6,0.000012,0.002579,0.000023,0.000140,0.407563,0.454902,0.345098,0.002797,0.949153,0.000064,1,0
3,17400985,23,6,0.000018,0.003906,0.000055,0.000174,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1,0
4,17401572,445,6,0.000041,0.008713,0.000082,0.000140,0.516807,0.905882,0.486275,0.009372,1.000000,0.000071,1,0

# Load data as a Heterogenous graph

Since lots of the GCN are built for undirected graphs, let's load the data as a heterogenous graph

Plan:
- Load each source ip -> destination port IF they actually have connection in dataset
- Set everything as source ip feature except int_source_ip and destination
- OHE the destination port to set it as categorical
- make one edge per src_ip and dest_port
- edge feature is protocol

make one edge per tcp(6), udp(17), icmp(1)

For each int_source_ip -> (protocol) -> destination_port, get the mean of everything

This to ensure only one edge per source and destination to avoid complications

In [31]:
grouped_df = proc_df.groupby(['int_source_ip', 'destination_port', 'protocol'])
grouped_df = grouped_df.mean().reset_index(drop=False)
grouped_df.head()

,int_source_ip,destination_port,protocol,num_scanned_destination_ips,num_unique_flows,num_packets,avg_packet_size,num_unique_Bs_scanned,num_unique_Cs_scanned,num_unique_Ds_scanned,num_scanned_24_blocks,time_activity,ip_scanned_rate,is_tcp,is_udp
0,16968188,23,6,0.000022,0.004822,0.000068,0.000174,0.731092,0.709804,0.690196,0.005244,1.000000,0.000067,1.0,0.0
1,17372742,445,6,0.000047,0.010086,0.000096,0.000140,0.521008,0.913725,0.490196,0.010870,1.000000,0.000073,1.0,0.0
2,17384594,445,6,0.000012,0.002579,0.000023,0.000140,0.407563,0.454902,0.345098,0.002797,0.949153,0.000064,1.0,0.0
3,17400985,23,6,0.000018,0.003906,0.000055,0.000174,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.0,0.0
4,17401572,445,6,0.000041,0.008713,0.000082,0.000140,0.516807,0.905882,0.486275,0.009372,1.000000,0.000071,1.0,0.0

In [32]:
grouped_df.shape

(132956, 15)

Get source feature names

In [42]:
src_node_featnames = proc_df.drop(columns=['int_source_ip', 'destination_port', 'protocol']).columns.tolist()
src_node_featnames

['num_scanned_destination_ips',
 'num_unique_flows',
 'num_packets',
 'avg_packet_size',
 'num_unique_Bs_scanned',
 'num_unique_Cs_scanned',
 'num_unique_Ds_scanned',
 'num_scanned_24_blocks',
 'time_activity',
 'ip_scanned_rate',
 'is_tcp',
 'is_udp']

Get unique destination ports

In [37]:
destination_ports = grouped_df['destination_port'].unique()
dest_features = [[port] for port in destination_ports]
dest_port_to_idx = {port: idx for idx, port in enumerate(destination_ports)}

dest_features[:3]

[[np.int64(23)], [np.int64(445)], [np.int64(0)]]

Get connections

In [38]:
src_indices = grouped_df['int_source_ip'].index.tolist()
dest_indices = grouped_df['destination_port'].map(lambda port: dest_port_to_idx[port]).tolist()
edge_protocols = grouped_df['protocol'].tolist()

In [62]:
# tcp_src = grouped_df.loc[grouped_df['protocol'] == 6, 'int_source_ip'].index.tolist()
# tcp_dest = grouped_df.loc[grouped_df['protocol'] == 6, 'destination_port'].map(lambda port: dest_port_to_idx[port]).tolist()

# udp_src = grouped_df.loc[grouped_df['protocol'] == 17, 'int_source_ip'].index.tolist()
# udp_dest = grouped_df.loc[grouped_df['protocol'] == 17, 'destination_port'].map(lambda port: dest_port_to_idx[port]).tolist()

# icmp_src = grouped_df.loc[grouped_df['protocol'] == 1, 'int_source_ip'].index.tolist()
# icmp_dest = grouped_df.loc[grouped_df['protocol'] == 1, 'destination_port'].map(lambda port: dest_port_to_idx[port]).tolist()

Keep only one edge per source_ip to destination_port

In [63]:
from torch_geometric.data import HeteroData
import torch

data = HeteroData()
source_ip_feats = grouped_df[src_node_featnames].values

# assign source edges x and y
data['source_ip'].x = torch.tensor(source_ip_feats, dtype=torch.float)
data['source_ip'].num_nodes = len(source_ip_feats)

# create destination ports
data['dest_ports'].x = torch.tensor(dest_features, dtype=torch.long)
data['dest_ports'].num_nodes = len(dest_features)

# # create connections
# data['source_ip', 'scans_tcp', 'dest_ports'].edge_index = torch.tensor(
#     [tcp_src, tcp_dest], dtype=torch.long
# )

# data['source_ip', 'scans_udp', 'dest_ports'].edge_index = torch.tensor(
#     [udp_src, udp_dest], dtype=torch.long
# )

# data['source_ip', 'scans_icmp', 'dest_ports'].edge_index = torch.tensor(
#     [icmp_src, icmp_dest], dtype=torch.long
# )

data['source_ip', 'scans', 'dest_ports'].edge_index = torch.tensor(
    [src_indices, dest_indices], dtype=torch.long
)

# data['source_ip', 'scans', 'dest_ports'].edge_attr = torch.tensor(
#     edge_protocols, dtype=torch.float
# )

# data['source_ip', 'scans', 'dest_ports'].edge_weight = torch.tensor(
#     torch.ones((len(edge_protocols))), dtype=torch.float
# )

data

HeteroData(
  source_ip={
    x=[132956, 12],
    num_nodes=132956,
  },
  dest_ports={
    x=[704, 1],
    num_nodes=704,
  },
  (source_ip, scans, dest_ports)={ edge_index=[2, 132956] }
)

# Split train test

> https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.transforms.RandomLinkSplit.html#torch_geometric.transforms.RandomLinkSplit

In [64]:
# from torch_geometric.transforms import RandomLinkSplit

# transform = RandomLinkSplit(is_undirected=False,
#                             num_val=0.1,
#                             num_test=0.2,
#                             edge_types=data.edge_types)

# doesn't work!
# train_data, val_data, test_data = transform(data)

# just use pytorch functions
split_perc = 0.8
num_nodes = data['source_ip'].num_nodes
perm = torch.randperm(num_nodes)
train_size = int(split_perc * num_nodes)
train_idx = perm[:train_size]
test_idx = perm[train_size:]

train_mask = torch.zeros(num_nodes, dtype=torch.bool)
test_mask = torch.zeros(num_nodes, dtype=torch.bool)
train_mask[train_idx] = True
test_mask[test_idx] = True

data['source_ip'].train_mask = train_mask
data['source_ip'].test_mask = test_mask

In [65]:
data

HeteroData(
  source_ip={
    x=[132956, 12],
    num_nodes=132956,
    train_mask=[132956],
    test_mask=[132956],
  },
  dest_ports={
    x=[704, 1],
    num_nodes=704,
  },
  (source_ip, scans, dest_ports)={ edge_index=[2, 132956] }
)

# Convert to undirected

Most of the GCN works for undirected graphs, so have to make it undirected

In [66]:
from torch_geometric.transforms import ToUndirected

undirected_transform = ToUndirected()
data = undirected_transform(data)

In [67]:
data.metadata()

(['source_ip', 'dest_ports'],
 [('source_ip', 'scans', 'dest_ports'),
  ('dest_ports', 'rev_scans', 'source_ip')])

# Model

We're going to try a shallow approach:
- Shallow: MetaPath2Vec (Node2Vec for heterogenous graphs)

deep approach might be promising, but next steps!
- Deep: Simple GraphSAGE GNN

> https://pytorch-geometric.readthedocs.io/en/latest/tutorial/heterogeneous.html

## Shallow: MetaPath2Vec

> https://pytorch-geometric.readthedocs.io/en/stable/tutorial/shallow_node_embeddings.html

> https://pytorch-geometric.readthedocs.io/en/stable/generated/torch_geometric.nn.models.MetaPath2Vec.html#torch_geometric.nn.models.MetaPath2Vec

> https://github.com/pyg-team/pytorch_geometric/blob/master/examples/hetero/metapath2vec.py

In [68]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [91]:
from torch_geometric.nn import MetaPath2Vec

# similar to
# https://github.com/pyg-team/pytorch_geometric/blob/master/examples/hetero/metapath2vec.py
embedding_dim = 64
walk_length = 10  # lower because it's a bipartite graph
context_size = 3
walks_per_node = 10
num_negative_samples = 5

metapath = data.metadata()[1]
num_nodes_dict = {
    'source_ip': data['source_ip'].num_nodes,
    'dest_ports': data['dest_ports'].num_nodes
}

model = MetaPath2Vec(data.edge_index_dict,
                     embedding_dim,
                     metapath,
                     walk_length,
                     context_size,
                     walks_per_node=walks_per_node,
                     num_negative_samples=num_negative_samples,
                     num_nodes_dict=num_nodes_dict,
                     sparse=False).to(device)

Train

In [92]:
from tqdm import tqdm
loader = model.loader(batch_size=256, shuffle=True, num_workers=0)
optimizer = torch.optim.Adam(list(model.parameters()), lr=0.01)

# from
# https://github.com/pyg-team/pytorch_geometric/blob/master/examples/hetero/metapath2vec.py
def train(epoch, log_steps=100, eval_steps=2000):
    model.train()

    total_loss = 0
    for i, (pos_rw, neg_rw) in enumerate(loader):
        optimizer.zero_grad()
        loss = model.loss(pos_rw.to(device), neg_rw.to(device))
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        if (i + 1) % log_steps == 0:
            print(f'Epoch: {epoch}, Step: {i + 1:05d}/{len(loader)}, '
                  f'Loss: {total_loss / log_steps:.4f}')
            total_loss = 0

In [93]:
EPOCHS = 7
for epoch in range(0, EPOCHS):
    train(epoch)

Epoch: 0, Step: 00100/520, Loss: 4.1993
Epoch: 0, Step: 00200/520, Loss: 2.4358
Epoch: 0, Step: 00300/520, Loss: 1.9194
Epoch: 0, Step: 00400/520, Loss: 1.6932
Epoch: 0, Step: 00500/520, Loss: 1.5383
Epoch: 1, Step: 00100/520, Loss: 1.3850
Epoch: 1, Step: 00200/520, Loss: 1.2876
Epoch: 1, Step: 00300/520, Loss: 1.2107
Epoch: 1, Step: 00400/520, Loss: 1.1480
Epoch: 1, Step: 00500/520, Loss: 1.0959
Epoch: 2, Step: 00100/520, Loss: 1.0426
Epoch: 2, Step: 00200/520, Loss: 1.0073
Epoch: 2, Step: 00300/520, Loss: 0.9764
Epoch: 2, Step: 00400/520, Loss: 0.9488
Epoch: 2, Step: 00500/520, Loss: 0.9266
Epoch: 3, Step: 00100/520, Loss: 0.9027
Epoch: 3, Step: 00200/520, Loss: 0.8867
Epoch: 3, Step: 00300/520, Loss: 0.8734
Epoch: 3, Step: 00400/520, Loss: 0.8616
Epoch: 3, Step: 00500/520, Loss: 0.8527
Epoch: 4, Step: 00100/520, Loss: 0.8421
Epoch: 4, Step: 00200/520, Loss: 0.8359
Epoch: 4, Step: 00300/520, Loss: 0.8307
Epoch: 4, Step: 00400/520, Loss: 0.8257
Epoch: 4, Step: 00500/520, Loss: 0.8229
Epoch: 5, Step: 00100/520, Loss: 0.8180
Epoch: 5, Step: 00200/520, Loss: 0.8153
Epoch: 5, Step: 00300/520, Loss: 0.8131
Epoch: 5, Step: 00400/520, Loss: 0.8111
Epoch: 5, Step: 00500/520, Loss: 0.8100
Epoch: 6, Step: 00100/520, Loss: 0.8078
Epoch: 6, Step: 00200/520, Loss: 0.8069
Epoch: 6, Step: 00300/520, Loss: 0.8061
Epoch: 6, Step: 00400/520, Loss: 0.8053
Epoch: 6, Step: 00500/520, Loss: 0.8041

In [97]:
torch.save(model.state_dict(), MODEL_FOLDER / 'metapath2vec_model_3.pth')

Get embeddings

In [98]:
model.eval()
with torch.no_grad():
    source_ip_embeddings = model('source_ip')

In [99]:
torch.save(source_ip_embeddings, DATA_FOLDER / "source_ip_embeddings_3.pt")

## INCOMPLETE: GraphSAGE

In [ ]:
from torch_geometric.nn import SAGEConv, to_hetero
import torch.nn.functional as F

# from link above
class GNN(torch.nn.Module):
    def __init__(self, hidden_channels, out_channels):
        super().__init__()
        self.conv1 = SAGEConv((-1, -1), hidden_channels)
        self.conv2 = SAGEConv((-1, -1), out_channels)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index).relu()
        x = self.conv2(x, edge_index)
        return x

In [ ]:
num_classes = data['source_ip'].y.max().item() + 1
num_classes

2

In [ ]:
model = GNN(hidden_channels = 64, out_channels=num_classes)
model = to_hetero(model, data.metadata(), aggr='sum')

/usr/local/lib/python3.11/dist-packages/torch_geometric/nn/to_hetero_transformer.py:156: UserWarning: There exist node types ({'source_ip'}) whose representations do not get updated during message passing as they do not occur as destination type in any edge type. This may lead to unexpected behavior.
  warnings.warn(

ValueError: Cannot generate a graph node 'relu' for type 'source_ip' since it does not exist. Please make sure that all node types get updated during message passing.