In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Purpose of Notebook

To see if anything of the ground truth from DarkVec is evaluated

In [3]:
from pathlib import Path
DATA_FOLDER = Path("/content/drive/MyDrive/DSCI599/data")

assert DATA_FOLDER.exists()

In [6]:
import pandas as pd

df_path = DATA_FOLDER / "1464217200.csv"
df = pd.read_csv(df_path)

df.head()

,int_source_ip,destination_port,protocol,num_scanned_destination_ips,num_unique_flows,num_packets,same_packet_size_flag,avg_packet_size,num_unique_Bs_scanned,num_unique_Cs_scanned,num_unique_Ds_scanned,num_scanned_24_blocks,num_non_conficker_destinations,time_activity,ip_scanned_rate
0,16968188,23,6,316.0,316.0,945.0,1.0,60.0,175.0,182.0,177.0,316.0,65.0,3540.0,0.089266
1,17372742,445,6,661.0,661.0,1322.0,1.0,48.0,125.0,234.0,126.0,654.0,661.0,3540.0,0.186723
2,17384594,445,6,169.0,169.0,329.0,1.0,48.0,98.0,117.0,89.0,169.0,169.0,3360.0,0.050298
3,17400985,23,6,256.0,256.0,762.0,1.0,60.0,1.0,1.0,256.0,1.0,128.0,0.0,-1.000000
4,17401572,445,6,571.0,571.0,1142.0,1.0,48.0,124.0,232.0,125.0,564.0,571.0,3540.0,0.161299

In [5]:
import pandas as pd
GT = DATA_FOLDER / "big_gt.csv"

gt = pd.read_csv(GT, header=0)
gt.head()

           ip        class
0  71.6.232.5  quadmetrics
1  71.6.232.4  quadmetrics
2  71.6.232.6  quadmetrics
3  71.6.232.7  quadmetrics
4  71.6.232.8  quadmetrics

In [20]:
import ipaddress

def conv_ip_intip(ip: str):
  assert type(ip) == str
  return int(ipaddress.ip_address(ip.strip()))

gt['int_ip'] = gt['ip'].apply(conv_ip_intip)

gt.head()

           ip        class      int_ip
0  71.6.232.5  quadmetrics  1191634949
1  71.6.232.4  quadmetrics  1191634948
2  71.6.232.6  quadmetrics  1191634950
3  71.6.232.7  quadmetrics  1191634951
4  71.6.232.8  quadmetrics  1191634952

In [38]:
left = df.rename(columns={'int_source_ip': 'ip'})
left['ip'] = left['ip'].astype('int')

right = gt[['int_ip', 'class']].rename(columns={'int_ip': 'ip'})

join = left.merge(right,
        on='ip',
        how='inner')
join.loc[~join['class'].isna(), :]

,ip,destination_port,protocol,num_scanned_destination_ips,num_unique_flows,num_packets,same_packet_size_flag,avg_packet_size,num_unique_Bs_scanned,num_unique_Cs_scanned,num_unique_Ds_scanned,num_scanned_24_blocks,num_non_conficker_destinations,time_activity,ip_scanned_rate,class
0,1123074186,7,17,220.0,220.0,220.0,1.0,32.0,149.0,145.0,151.0,219.0,56.0,3540.0,0.062147,shodan
1,1123074186,7,17,220.0,220.0,220.0,1.0,32.0,149.0,145.0,151.0,219.0,56.0,3540.0,0.062147,shodan
2,1123074186,11,6,236.0,236.0,236.0,1.0,40.0,142.0,151.0,139.0,236.0,69.0,3540.0,0.066667,shodan
3,1123074186,11,6,236.0,236.0,236.0,1.0,40.0,142.0,151.0,139.0,236.0,69.0,3540.0,0.066667,shodan
4,1123074186,13,6,258.0,258.0,258.0,1.0,40.0,160.0,165.0,165.0,258.0,53.0,3540.0,0.072881,shodan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6795,3323224962,55554,6,723.0,723.0,723.0,1.0,40.0,226.0,240.0,240.0,719.0,206.0,3540.0,0.204237,shodan
6796,3323224962,62078,6,706.0,706.0,706.0,1.0,40.0,225.0,242.0,243.0,702.0,192.0,3540.0,0.199435,shodan
6797,3323224962,62078,6,706.0,706.0,706.0,1.0,40.0,225.0,242.0,243.0,702.0,192.0,3540.0,0.199435,shodan
6798,3323224962,64738,17,673.0,673.0,673.0,1.0,40.0,223.0,240.0,235.0,671.0,180.0,3540.0,0.190113,shodan
6799,3323224962,64738,17,673.0,673.0,673.0,1.0,40.0,223.0,240.0,235.0,671.0,180.0,3540.0,0.190113,shodan

In [40]:
join['class'] = join['class'].fillna("Unknown")
join['class'].value_counts()

class
shodan    6706
u_mich      94
Name: count, dtype: int64

In [41]:
df['protocol'].value_counts()

protocol
6     109596
17     21136
1       2224
Name: count, dtype: int64

In [29]:
int_ip = set(gt['int_ip'].tolist())
df['int_source_ip'].apply(lambda ip: ip in int_ip).sum()

np.int64(3963)

In [ ]:
df['']